FROM adoptopenjdk/openjdk11:jre-11.0.14_9-alpine

ARG FLYWAY_VERSION=8.5.0

# Install flyway
RUN apk add --no-cache bash \
    && mkdir /flyway

WORKDIR /flyway

RUN wget -q https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -O flyway-commandline-${FLYWAY_VERSION}.tar.gz \
    && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 \
    && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz

WORKDIR /

RUN mkdir /db

COPY ./db-migration/src/main/resources/db/* /db/

ENTRYPOINT ["/bin/bash", "-c", "/flyway/flyway migrate"]
