version: '3.1'

services:
  boilerplate-db:
    image: postgres:14-alpine
    container_name: boilerplate-db
    environment:
      POSTGRES_USER: "localdev"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db-password"
      POSTGRES_DB: "boilerplate"
    ports:
      - 7030:5432
    volumes:
      - ./docker-secrets:/run/secrets
      - boilerplate-db-data:/var/lib/postgresql/data
volumes:
  boilerplate-db-data:
    external: true