version: '3.1'

services:
  local-test-db:
    image: postgres:14-alpine
    container_name: local-test-db
    environment:
      POSTGRES_USER: "local-test"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db-password"
      POSTGRES_DB: "local-test"
    ports:
      - 3333:5432
    volumes:
      - ./docker-secrets:/run/secrets
      - local-test-db-data:/var/lib/postgresql/data
volumes:
  local-test-db-data:
    external: true